name: ${project.name}
main: com.untamedears.humbug.Humbug
version: ${project.version}
softdepend: [CombatTag, CombatTagPlus]
description: toggles various functionality
author: erocs
authors: [ProgrammerDan, rourke750]
database: false
commands:
  humbug:
    description: Gets and sets Humbugs settings
    usage: /humbug <setting> [<value>]
    permission: humbug.console
  bahhumbug:
    description: Creates a holiday package
    usage: /bahhumbug
    permission: humbug.admin.bahhumbug
permissions:
  humbug.console:
    description: Console commands for Humbug
    default: false
  humbug.admin:
    description: Admin commands for Humbug
    default: op
    children:
      humbug.admin.bahhumbug: true
  humbug.admin.bahhumbug:
    description: Access to the /bahhumbug command
    default: false
